services:
  naud-thai-web-dev:
    build: .
    container_name: naud-thai-web-dev
    restart: unless-stopped
    networks:
      - hosting
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.naud-thai-web-dev.rule=Host(`dev-naud.zunkireelabs.com`)"
      - "traefik.http.routers.naud-thai-web-dev.entrypoints=websecure"
      - "traefik.http.routers.naud-thai-web-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.naud-thai-web-dev.loadbalancer.server.port=80"

networks:
  hosting:
    external: true
